src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="user")
     */
    private $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getRole(): ?string
    {
        $userRoles = $this->getRoles();
        $access = implode(',', $userRoles);
        $admin = 'Admin';
        $user = 'User';

        switch ($access) {
            case 'ROLE_ADMIN,ROLE_USER':
                return $admin;
                break;
                case 'ROLE_USER':
                    return $user;
                    break;
        }
        
        return '';
    }

    

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Product;
use App\Entity\Category;
use App\Form\ProductType;
use App\Form\CategoryType;
use App\Form\RegisterType;
use App\Form\EditUsersType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class DashboardController extends AbstractController
{

    public function __construct(EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher)
    {

        $this->entityManager = $entityManager;
        $this->passwordHasher = $passwordHasher;
    }
    /**
     * @Route("/admin/dashboard", name="dashboard")
     */
    public function dashboard(): Response
    {

        $users = $this->entityManager->getRepository(User::class)->findAll();
        $products = $this->entityManager->getRepository(Product::class)->findAll();
        $categories = $this->entityManager->getRepository(Category::class)->findAll();

        return $this->render('dashboard/dashboard.html.twig', [
            'users' => $users,
            'products' => $products,
            'categories' => $categories
        ]);
    }

    /**
     * @Route("admin/add/user", name="add_user")
     */
    public function addUser(Request $request): Response
    {

        $user = new User();
        $form = $this->createForm(RegisterType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user = $form->getData();
            $user->setPassword($this->passwordHasher->hashPassword($user, $user->getPassword()));
            $this->entityManager->persist($user);
            $this->entityManager->flush();
            return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
        }

        return $this->render('dashboard/addUsers.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/edit/user/{id}", name="edit_user")
     */
    public function editUser($id, Request $request): Response
    {

        $users = $this->entityManager->getRepository(User::class)->find($id);

        $form = $this->createForm(EditUsersType::class, $users);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $users->setPassword($this->passwordHasher->hashPassword($users, $users->getPassword()));
            $this->entityManager->persist($users);
            $this->entityManager->flush();
            return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
        }




        return $this->render('dashboard/editUsers.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/delete/user/{id}", name="delete_user")
     */
    public function deleteUser(User $users, Request $request): Response
    {

        $this->entityManager->remove($users);
        $this->entityManager->flush();
        $this->addFlash('success', 'Membre supprimé !');





        return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
    }

    /**
     * @Route("admin/add/product", name="add_product")
     */
    public function addProduct(Request $request): Response
    {

        $product = new product();
        $form = $this->createForm(ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $product = $form->getData();
            $this->entityManager->persist($product);
            $this->entityManager->flush();
            return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
        }

        return $this->render('dashboard/addproducts.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/edit/product/{id}", name="edit_product")
     */
    public function editProduct($id, Request $request): Response
    {

        $products = $this->entityManager->getRepository(product::class)->find($id);

        $form = $this->createForm(ProductType::class, $products);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($products);
            $this->entityManager->flush();
            return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
        }




        return $this->render('dashboard/editproducts.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/delete/product/{id}", name="delete_product")
     */
    public function deleteproduct(product $products, Request $request): Response
    {

        $this->entityManager->remove($products);
        $this->entityManager->flush();
        $this->addFlash('success', 'Membre supprimé !');





        return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
    }

    /**
     * @Route("admin/add/category", name="add_category")
     */
    public function addCategory(Request $request): Response
    {

        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $category = $form->getData();
            $this->entityManager->persist($category);
            $this->entityManager->flush();
            return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
        }

        return $this->render('dashboard/addcategories.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/edit/category/{id}", name="edit_category")
     */
    public function editCategory($id, Request $request): Response
    {

        $categories = $this->entityManager->getRepository(Category::class)->find($id);

        $form = $this->createForm(CategoryType::class, $categories);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->persist($categories);
            $this->entityManager->flush();
            return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
        }




        return $this->render('dashboard/editcategories.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/delete/category/{id}", name="delete_category")
     */
    public function deleteCategory(Category $categories, Request $request): Response
    {

        $this->entityManager->remove($categories);
        $this->entityManager->flush();
        $this->addFlash('success', 'Membre supprimé !');





        return $this->redirect($request->get('redirect') ?? '/admin/dashboard');
    }
}

templates/dashboard/addCategories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter catégorie - Apple{% endblock %}

{% block body %}

<section class="vh-100 bg-image" style="background-color: #C7C8C9;">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Ajouter une catégorie</h2>

             {{form(form)}}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/dashboard/addProducts.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter produit - Apple{% endblock %}

{% block body %}

<section class="vh-100 bg-image" style="background-color: #C7C8C9;">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Ajouter un produit</h2>

             {{form(form)}}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/dashboard/addUsers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter membre - Apple{% endblock %}

{% block body %}

<section class="vh-100 bg-image" style="background-color: #C7C8C9;">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Inscription</h2>

             {{form(form)}}

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/dashboard/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Espace Administrateur{% endblock %}

{% block body %}
<div class="container">
    <h2 class="text-center">Mes membres</h2>
    <a href="{{path('add_user')}}" class="btn mb-2 mb-md-0 btn-outline-secondary btn-block">Ajouter un membre</a>
    <table class="table table-hover mt-2">
        <thead class="table-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Prénom</th>
                <th scope="col">Nom</th>
                <th scope="col">Email</th>
                <th scope="col">Rôle</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <th>{{user.id}}</th>
                <td>{{user.firstname}}</td>
                <td>{{user.lastname}}</td>
                <td>{{user.email}}</td>
                <td>{{user.role}}</td>
                <td>
                    <a href="{{path('edit_user',{'id': user.id})}}"><i style="color: black;" class="bi bi-pencil-square"></i></a> |
                    <a href="{{path('delete_user',{'id': user.id})}}"><i style="color: black;" class="bi bi-trash"></i></a>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>

     <h2 class="text-center">Mes produits</h2>
    <a href="{{path('add_product')}}" class="btn mb-2 mb-md-0 btn-outline-secondary btn-block">Ajouter un produit</a>
    <table class="table table-hover mt-2">
        <thead class="table-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nom du produit</th>
                <th scope="col">Couleur</th>
                <th scope="col">Description</th>
                <th scope="col">Photo</th>
                <th scope="col">Capacité</th>
                <th scope="col">Prix</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <th>{{product.id}}</th>
                <td>{{product.name}}</td>
                <td>{{product.color}}</td>
                <td>{{product.description}}</td>
                <td> <img style="width:150px; height: 150px;" src="{{product.picture}}" alt=""> </td>
                <td>{{product.capacity}}</td>
                <td>{{product.price}}€</td>
                <td>{{product.category}}</td>
                <td>
                     <a href="{{path('edit_product',{'id': product.id})}}"><i style="color: black;" class="bi bi-pencil-square"></i></a> | 
                     <a href="{{path('delete_product',{'id': product.id})}}"><i style="color: black;" class="bi bi-trash"></i></a> 
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h2 class="text-center">Mes catégories</h2>
    <a href="{{path('add_category')}}" class="btn mb-2 mb-md-0 btn-outline-secondary btn-block">Ajouter une catégorie</a>
    <table class="table table-hover mt-2">
        <thead class="table-dark">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Catégorie</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
            <tr>
                <th>{{category.id}}</th>
                <td>{{category.name}}</td>
                
                <td>
                     <a href="{{path('edit_category',{'id': category.id})}}"><i style="color: black;" class="bi bi-pencil-square"></i></a> | 
                     <a href="{{path('delete_category',{'id': category.id})}}"><i style="color: black;" class="bi bi-trash"></i></a> 
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>


{% endblock %}

templates/dashboard/editCategories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier catégorie - Apple{% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card-body p-5">

                {{form(form)}}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/editProducts.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier produit - Apple{% endblock %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card-body p-5">

                {{form(form)}}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/editUsers.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier membre - Apple{% endblock %}

{% block body %}

{% if app.user and app.user.role == 'Admin' %}

<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card-body p-5">

                {{form(form)}}
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock %}